name: schedule

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      
      - name: Run search
        env: 
          barkToken: ${{secrets.BARK_TOKEN}}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          go build search.go utils.go
          ./search
          rm search
          git add .
          git commit --allow-empty -m "Auto Update `date --rfc-3339=seconds`"
          git push -f
